ALTER TABLE EMPRESAS_PARAMETROS DROP TPNFDEBITO;
ALTER TABLE EMPRESAS_PARAMETROS DROP TPNFCREDITO;
ALTER TABLE EMPRESAS_PARAMETROS DROP TPENTEGOV;
ALTER TABLE EMPRESAS_PARAMETROS DROP TPOPERGOV;

ALTER TABLE EMPRESAS_PARAMETROS ADD TPNFDEBITO VARCHAR_2;
ALTER TABLE EMPRESAS_PARAMETROS ADD TPNFCREDITO VARCHAR_2;
ALTER TABLE EMPRESAS_PARAMETROS ADD TPENTEGOV VARCHAR_2;
ALTER TABLE EMPRESAS_PARAMETROS ADD TPOPERGOV VARCHAR_2;

ALTER TABLE VENDAS DROP TPNFDEBITO;
ALTER TABLE VENDAS DROP TPNFCREDITO;
ALTER TABLE VENDAS DROP TPENTEGOV;
ALTER TABLE VENDAS DROP TPOPERGOV;

ALTER TABLE VENDAS ADD TPNFDEBITO VARCHAR_2;
ALTER TABLE VENDAS ADD TPNFCREDITO VARCHAR_2;
ALTER TABLE VENDAS ADD TPENTEGOV VARCHAR_2;
ALTER TABLE VENDAS ADD TPOPERGOV VARCHAR_2;

-- Indicador de fornecimento de bem móvel usado
ALTER TABLE ITENS_VENDA ADD IndBemMovelUsado VARCHAR_1;
ALTER TABLE PRODUTOS    ADD IndBemMovelUsado SMALLINT_;

ALTER TABLE PRODUTOS ADD ISel_CSTIS VARCHAR_3;

ALTER TABLE PRODUTOS ADD ISel_cClassTribIS VARCHAR_10;
ALTER TABLE PRODUTOS ADD ISel_pIS   NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD ISel_pISEspec NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD ISel_uTrib VARCHAR_10;
ALTER TABLE PRODUTOS ADD ISel_qTrib NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD IBSCBS_cST VARCHAR_3;
ALTER TABLE PRODUTOS ADD IBSCBS_cClassTrib VARCHAR_10;

ALTER TABLE PRODUTOS ADD IBSUF_pIBSUF     NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD IBSUF_pAliqEfet  NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD IBSUF_pDIF       NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD IBSUF_pRedAliq   NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD IBSMUN_pIBSMUN   NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD IBSMUN_pAliqEfet NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD IBSMUN_pDif      NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD IBSMUN_pRedAliq  NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD CBS_pCBS      NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD CBS_pDIF      NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD CBS_pRedAliq  NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD CBS_pAliqEfet NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD CSTReg             VARCHAR_3;   --> IBSCBS.gIBSCBS.gTribRegular.CSTReg
ALTER TABLE PRODUTOS ADD cClassTribReg      VARCHAR_10;  --> IBSCBS.gIBSCBS.gTribRegular.cClassTribReg
ALTER TABLE PRODUTOS ADD pAliqEfetRegCBS    NUMERIC_18_4; --> IBSCBS.gIBSCBS.gTribRegular.pAliqEfetRegIBSUF
ALTER TABLE PRODUTOS ADD pAliqEfetRegIBSUF  NUMERIC_18_4; --> IBSCBS.gIBSCBS.gTribRegular.vTribRegIBSUF
ALTER TABLE PRODUTOS ADD pAliqEfetRegIBSMUN NUMERIC_18_4; --> IBSCBS.gIBSCBS.gTribRegular.pAliqEfetRegIBSMun

ALTER TABLE PRODUTOS ADD IBS_cCredPres VARCHAR_3;
ALTER TABLE PRODUTOS ADD IBS_pCredPres NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD CBS_cCredPres VARCHAR_3;
ALTER TABLE PRODUTOS ADD CBS_pCredPres NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD TCG_pAliqCBS    NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD TCG_pAliqIBSMun NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD TCG_pAliqIBSUF  NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD qBcMono         NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD AdRemIBS        NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD AdRemCBS        NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD qBcMonoReten  NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD AdRemIBSReten NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD AdRemCBSReten NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD qBcMonoRET  NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD AdRemCBSRet NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD AdRemIBSRet NUMERIC_18_4;

ALTER TABLE PRODUTOS ADD pDifCBSMono NUMERIC_18_4;
ALTER TABLE PRODUTOS ADD pDifIBSMono NUMERIC_18_4;